### ISSUE TITLE
Mod not showing in drop down menu

### ISSUE THREAD

**Issue by mawmz** [Alex4SSB/EU4-PCP#1]
Hi there, I believe I should have everything set up correctly as per following the user manual.

![image](https://github.com/Alex4SSB/EU4-PCP_WPF_NET5/assets/42359353/5ceeac6f-6288-4102-ae6e-f090aac0904b)
![image](https://github.com/Alex4SSB/EU4-PCP_WPF_NET5/assets/42359353/c4537bd9-07ba-4d84-ab19-d8a8182a3d6e)
![image](https://github.com/Alex4SSB/EU4-PCP_WPF_NET5/assets/42359353/d7622422-21db-4b24-a15c-2fe03afb8051)
![image](https://github.com/Alex4SSB/EU4-PCP_WPF_NET5/assets/42359353/0bb6843b-0a2f-4289-ab45-e235ba045fe8)
![image](https://github.com/Alex4SSB/EU4-PCP_WPF_NET5/assets/42359353/e3bca2a1-014a-4bd2-ba11-d56cac21ba13)

I'm absolutely stumped as to why this isn't working. Other mods in that dropdown menu, such as Extended Timeline, aren't appearing there either. I've done several clean reinstalls of the program and cannot figure this out. I'd appreciate any help.

**Comment by Alex4SSB** [comment]
Apparently the problem was with mods that have `supported_version="v1.xx.x"` - the app did not support the `v` in there.

It seems to be working now, it would help if you could check the fix with this test version, before I release it as an official one:
[EU4-PCP test version 2024-06-26.zip](https://github.com/user-attachments/files/15994588/EU4-PCP.test.version.2024-06-26.zip)

**Comment by mawmz** [comment]
works perfectly now, all downloaded mods now show in the dropdown menu. thanks!

![image](https://github.com/Alex4SSB/EU4-PCP_WPF_NET5/assets/42359353/a35f29ce-0993-44e8-af09-bc4f910ee473)

**Comment by Alex4SSB** [comment]
Thank you too! I will release a version soon.
