### ISSUE TITLE
eu4 pcp crashes on loading a .csv file

### ISSUE THREAD

**Issue by skrinop** [Alex4SSB/EU4-PCP#3]
Seemingly all mods, regardless of if they have a definition.csv file or not - including base game - will crash the app after a few seconds of loading. I've tried the solutions recommended in the user manual but to no success.

https://github.com/user-attachments/assets/668026f2-0021-4da1-af89-2fd09f6a7fd4

not sure how this occured or what could be crashing it.

**Comment by Alex4SSB** [comment]
Okay, I found the issue - this happens when the app is launched with Province Names set to "From Definition":

![image](https://github.com/user-attachments/assets/c79e940d-a4a4-4813-a657-47576c30dc2a)

If you just select "Dynamic", this should fix the problem, and after that you'll be able to open external definitions even for other Paradox games, like CK2.

I will fix this issue soon, thank you for reporting it!

**Comment by skrinop** [comment]
Yep that was it, enabling dynamic actually let's me load the files now. Thank you!

If possible - not sure if I should open a new issue - could you add the ability to copy the hex for a color just by right-clicking on said color in the province list, instead of having to click on the hex code itself?

**Comment by Alex4SSB** [comment]
The issue is fixed in the new version, and your additional feature is in as well.
